glacials/splits-io

- app/controllers/api/v3/users/games/categories/runs_controller.rb
Ad missing route /users/:user_id/games/:game_id/categories/:category_id/runs
> Add missing route

- app/controllers/api/v3/games/categories_controller.rb
- app/controllers/api/v4/games/categories_controller.rb
- docs/api.md
Fix /games/catogroies endpoint and update api docs example route
> Fix /games/categories

- app/controllers/runs_controller.rb
- app/models/run.rb
- app/views/runs/show.slim
- app/views/runs/urn.html.erb
> Urn download support

- app/assets/stylesheets/article.sass
> Dotted lines between articles no longer break

- Gemfile
- Gemfile.lock
- app/models/run_file.rb
Reverts glacials/splits-io#194
> Revert "Switch forms of binary detection"

- app/controllers/api/v4/converts_controller.rb
- app/controllers/converts_controller.rb
- app/models/run.rb
- app/views/converts/new.slim
- spec/controllers/api/v4/converts_controller_spec.rb
- spec/fixtures/files/malformed
More error checking and handling.
> Flesh out convert endpoints

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/date.coffee
- app/views/shared/_run_table.slim
> pass absolute dates in run table

- docs/api.md
Adds new fields reduced and history to split objects.  Adds new fields
attempts and sum_of_best to top object. Changed output to use the
example url.
> Update api docs

- app/views/runs/stats/index.slim
> Fix a rendering error in FF

- app/assets/javascripts/segment_history_graph.coffee
> Hide histories past 15 by default

- app/controllers/sessions_controller.rb
- app/controllers/users/rivalries_controller.rb
- app/models/user.rb
- app/views/layouts/application.slim
- app/views/settings/index.slim
- db/migrate/20170209005256_add_display_name_to_users.rb
- db/schema.rb
> Use display name throughout the app

- app/assets/javascripts/reset_graph.coffee
> Fix reset graph math

- .travis.yml
- Gemfile.lock
Also use quiet option in fake-s3, which silences some output.
> Add env variables to travis.yml

- app/assets/javascripts/reset_graph.coffee
- app/assets/javascripts/segment_history_graph.coffee
- app/controllers/runs/stats_controller.rb
- app/models/concerns/completed_run.rb
- app/views/runs/stats/index.slim
> Add total playtime to the stats page

- README.md
- app/models/concerns/twitch_user.rb
- lib/twitch.rb
> Use twitch api v5 and twitch ids instead of usernames

- app/models/game.rb
> Use case insensitive search

- app/views/layouts/application.slim
> Add search to navbar

- app/models/concerns/rival_user.rb
- app/models/concerns/twitch_user.rb
> Add cache timeout for follows

- app/assets/javascripts/analytics.js
> Fix GA error

- app/models/concerns/completed_run.rb
- app/models/run_history.rb
- app/views/runs/llanfair_gered.html.erb
- lib/programs/llanfair_gered.rb
> Add ability to export to llanfair-gered

- Dockerfile
- config/database.yml
- db/init.sql
- docker-compose.yml
This makes it much easier to examine stuff in the rails console without having hundreds of test users, games, and categories filling up the queries instead of the data you want to test stuff with.
> Use separate databases for each environment

- Dockerfile
- Dockerfile-production
- docker-compose-production.yml
- docker-compose.yml
For some reason when you run yarn install from the dockerfile it doesn't actually create a node_modules folder or install anything
> Fix yarn install

- Dockerfile
- Dockerfile-production
Use best practices in dockerfile as well
> Speed up docker builds for machines with more than 2 cores

- app/controllers/runs/stats_controller.rb
- app/controllers/runs_controller.rb
- app/views/runs/_timing_switch.slim
27 queries -> 14, time switcher >200ms -> <10ms
> Optimize stats page

- app/models/run.rb
- spec/models/run_spec.rb
Seems like it behaves differently then fakes3.  This also cleans up some of the rubocop errors in run.rb.
> Fix s3 error in production

- app/models/concerns/unparsed_run.rb
> Reject splits with 0 segments

- lib/speedrundotcom.rb
> Update regex for new format

- app/controllers/runs_controller.rb
> Update error srdc url

- app/controllers/api/v4/converts_controller.rb
- app/controllers/converts_controller.rb
- app/javascript/convert.js
- app/javascript/packs/application.js
- app/views/converts/new.slim
- config/routes.rb
- package.json
- yarn.lock
> Use js for the convert form

- app/controllers/api/v4/categories/runners_controller.rb
- app/controllers/api/v4/categories/runs_controller.rb
- app/controllers/api/v4/games/categories_controller.rb
- app/controllers/api/v4/games/runners_controller.rb
- app/controllers/api/v4/games/runs_controller.rb
- app/models/category.rb
- app/models/game.rb
- config/routes.rb
- docs/api_v4.md
- spec/controllers/api/v4/categories/runners_controller_spec.rb
- spec/controllers/api/v4/categories/runs_controller_spec.rb
- spec/controllers/api/v4/games/categories_controller_spec.rb
- spec/controllers/api/v4/games/runners_controller_spec.rb
- spec/controllers/api/v4/games/runs_controller_spec.rb
- spec/controllers/api/v4/games_controller_spec.rb
- spec/factories/category_factory.rb
- spec/factories/game_factory.rb
- spec/spec_helper.rb
- spec/support/models/api/v4/run.json
- spec/support/models/api/v4/segment.json
- spec/support/views/api/v4/categories/runners/index.json
- spec/support/views/api/v4/categories/runs/index.json
- spec/support/views/api/v4/games/categories/index.json
- spec/support/views/api/v4/games/runners/index.json
- spec/support/views/api/v4/games/runs/index.json
> Complete APIv4 according to readme specifications

- app/models/concerns/unparsed_run.rb
- spec/factories/run_factory.rb
- spec/factories/run_files/with_segments_bests.lss
- spec/models/run_spec.rb
Hi! First of all I just wanted to say - great codebase, it was super easy getting into and the fact all the environment is setup by Docker makes everything extremely simple 💯
I'll leave some open questions directly on the related lines, but overall if the fix makes sense then I wonder if you want a migration in order to fix previous runs. I honestly learned about the existence of this site _yesterday_ so I have no idea how much data is in there and how long would such a migration take to complete, but let me know your thoughts.
Fixes #334
> Correctly sum all segment's gameplay bests when parsing

- app/controllers/api/v3/application_controller.rb
- app/controllers/api/v3/runs_controller.rb
- app/controllers/api/v4/application_controller.rb
- app/controllers/health_controller.rb
Authie will still trigger session stuff if you visit it logged in while in a browser, but this should fix it for all consumers of the api.
> Optimize api stuff

- app/views/runs/stats/_segments.slim
- app/views/runs/stats/index.slim
Should be the last change to address everything in #371 .
> Use timing information for segment table on stats page

- app/models/concerns/unparsed_run.rb
- spec/models/run_spec.rb
Closes #372 .
I checked the test files manually to make sure that they did have negative attempts, everything checked out.
> Reject negative attempt counts

- app/assets/javascripts/spinner.coffee
- app/assets/javascripts/upload.coffee
Also automatically hide the spinner when empty uplaod is triggered.
> Fix hideSpinner function

- app/views/rivalries/index.slim
- app/views/shared/_follows.slim
Currently it looks super pushed together, this just adds a bit more space to match live site spacing.
> Minor bootstrap 4 update formatting mishaps

- app/assets/javascripts/follows.coffee
- app/controllers/users_controller.rb
- app/views/runs/index.slim
- app/views/shared/_follows.slim
- config/routes.rb
Since everything is local now, we can just render this with the original request with no hit to response time.  Closes #94 since it's no longer in a weird in between state.
> Move follow view code inline

- app/views/runs/_timeline.slim
> Display - on unnamed splits in timeline

- spec/views/search/index_spec.rb
- spec/views/settings/index_spec.rb
Missed 2 folders when I went through it the first time.
> Add missed view tests

- app/controllers/applications_controller.rb
- app/models/ability.rb
- app/views/applications/edit.slim
- app/views/applications/new.slim
- app/views/settings/index.slim
- config/routes.rb
- db/migrate/20180810055852_add_secret_generated_at_to_applications.rb
- db/schema.rb
Adds the ability to edit existing developer applications (changing name, changing redirect URI, resetting secrets). Fixes #430.
> Allow editing applications & resetting secrets

- app/models/category.rb
- app/models/concerns/completed_run.rb
- app/models/concerns/srl_game.rb
- app/models/game_alias.rb
- app/models/rivalry.rb
- app/models/twitch_user_follow.rb
- app/models/user.rb
Related to: https://github.com/glacials/splits-io/issues/331
Fixed rubocop errors in `app/models/.`
> Fix Rubocop errors in models

- app/dashboards/category_dashboard.rb
- app/dashboards/game_alias_dashboard.rb
- app/dashboards/game_dashboard.rb
- app/dashboards/patreon_user_dashboard.rb
- app/dashboards/rivalry_dashboard.rb
- app/dashboards/run_dashboard.rb
- app/dashboards/segment_dashboard.rb
- app/dashboards/segment_history_dashboard.rb
- app/dashboards/user_dashboard.rb
Related to: https://github.com/glacials/splits-io/issues/331
Fixed rubocop errors in `app/dashboards/.`
> Fix Rubocop errors in dashboards

- app/controllers/api/v3/application_controller.rb
- app/controllers/api/v3/games/categories/runs_controller.rb
- app/controllers/api/v3/games/categories_controller.rb
- app/controllers/api/v3/games/runs_controller.rb
- app/controllers/api/v3/games_controller.rb
- app/controllers/api/v3/runs_controller.rb
- app/controllers/api/v3/users/games/categories/pbs_controller.rb
- app/controllers/api/v3/users/games/categories/predictions_controller.rb
- app/controllers/api/v3/users/games/categories/runs_controller.rb
- app/controllers/api/v3/users/pbs_controller.rb
- app/controllers/api/v3/users/runs_controller.rb
- app/controllers/api/v3/users_controller.rb
- app/controllers/api/v4/application_controller.rb
- app/controllers/api/v4/converts_controller.rb
- app/controllers/api/v4/games_controller.rb
- app/controllers/api/v4/runs_controller.rb
Related to: https://github.com/glacials/splits-io/issues/331
Fixed rubocop errors in `app/controllers/api/.`
> Fix rubocop errors in controllers api dir

- public/schema/README.md
- public/schema/run_v1.0.0.json
Adds a canonical Splits I/O JSON schema specified by [json-schema][1].
[1]: http://json-schema.org/
> Splits I/O JSON Schema

- app/javascript/search.js
> Add check on typeahead to see if it is already added

- app/models/concerns/completed_run.rb
- app/models/concerns/unparsed_run.rb
- app/views/runs/_quick_stats.slim
- app/views/runs/stats/index.slim
- db/migrate/20181012004151_add_total_playtime_ms.rb
- db/schema.rb
- lib/parser/livesplit_core_parser.rb
- spec/factories/run_factory.rb
- spec/models/run_spec.rb
> Use livesplit-core analysis module for SoB and total playtime

- Makefile
Make the attach command behave the same as all the rest (deferring to sudo on linux) and remove an extra seed call and duplicated echo.
> Makefile updates and cleanup

- Gemfile
- Gemfile.lock
- app/views/doorkeeper/authorizations/show.slim
- config/initializers/mini_profiler.rb
Hopefully this will fix the production boxes running out of file system storage (#546 ), or help prevent some of it.
> Update gems to fix revision not found, use redis store for profiler

- app/controllers/api/v4/application_controller.rb
- app/controllers/api/v4/games_controller.rb
- docs/api.md
- spec/controllers/api/v4/games_controller_spec.rb
Closes #489 
Piggybacking 2 other API doc tweaks onto this.
> Allow game lookup by ID in APIv4

- Makefile
Add phony's for all tasks, repurpose `all` to build and run the app, stop containers after building to get a clean start.
Closes #576
> Adjust makefile behavior

- app/jobs/race_cleanup_job.rb
- app/models/entry.rb
- app/models/race.rb
- app/views/races/index.slim
- docker-compose-production.yml
- docker-compose.yml
After a race has been going for 48 hours, forcefully forfeit all entries that have not finished or forfeited already.
The longest recorded 602 time is 47 hours :)
> Clean up started but abandoned races

- app/controllers/api/v4/runs_controller.rb
- app/jobs/run_cleanup_job.rb
- db/migrate/20191006212943_cleanup_runs_with_no_files.rb
- db/schema.rb
- docker-compose-production.yml
- docker-compose.yml
I'm not sure why the GitHub actions are failing, since it works perfectly fine locally and the error doesn't make a lot of sense to me.
> Clear fileless runs, and add job to delete new ones after an hour

- app/views/shared/_twitter_card.slim
Wasn't sure if this was the content you had in mind, or if you wanted something more dynamic (ex: entrant count, race status, etc...).
Closes #575
> Add basic twitter/discord embed metadata

- app/models/highlight_suggestion.rb
> Guard against twitch highlight errors

- Gemfile
- Gemfile.lock
- app/controllers/search_controller.rb
- app/javascript/like.js
- app/models/category.rb
- app/models/run.rb
- app/views/games/categories/_title.slim
- app/views/games/categories/leaderboards/sum_of_bests/index.slim
- app/views/games/categories/show.slim
- app/views/games/edit.slim
- app/views/races/_create.slim
- app/views/runs/_compare_button.slim
- app/views/runs/_export_button.slim
- app/views/runs/_title.slim
- app/views/runs/index.slim
- app/views/search/index.slim
- app/views/shared/_run_table.slim
- db/seeds.rb
- public/500.html
Adds game box art, condenses export / race buttons, adds Twitch links, and adds some basic information about median run lengths to the game page.
> Update game page design

- app/controllers/api/v4/games/categories_controller.rb
- app/models/category.rb
- app/models/game.rb
- docs/api.md
Added optional parameter to API that only returns categories with at least one run (see #716 )
- Updated API documentation to reflect this change
> Added optional parameter to API that only returns categories with at least one run
