app/views/runs/not_found.slim
The email link on the 404 page https://splits.io/notALink is broken. This fixes it.
=> Fix broken email link on 404 page

app/views/users/pbs/export/panels/index.erb
Resolves #148 by adding an addition column "Video" with "Watch" links when there is a proof video for the run.
=> Add Video link to Twitch panel export

Gemfile, Gemfile.lock, app/models/run_file.rb
ptools was not flagging all llanfair files as binary, filemagic seems to
be the more accurate version of checking file types.
=> Switch forms of binary detection

app/models/run_file.rb
This takes away the libmagic dependency, and all of my llanfair files
have more than one null byte that doesn't change positions between
files.  Should be more accurate than ptools as well.
=> Scan uploads for null bytes

app/models/run_file.rb
I tested this with every llanfair file I have (around 20) and it worked
fine.  I assume this come from the object serialization of the run
object.
=> Stop scanning the whole file to check if llanfair

app/models/concerns/unparsed_run.rb
Runs will redirect to cant_parse_path instead of 500'ing
=> Return nil instead of raising error

app/assets/javascripts/run_claim.coffee, app/controllers/application_controller.rb, app/controllers/runs/stats_controller.rb, app/controllers/runs_controller.rb, app/views/runs/_title.slim, app/views/runs/show.slim, app/views/runs/stats/index.slim
Allows users to self-claim runs they uploaded while logged out, which is the most common support request I get from people that I have to fulfill manually.
Somehow I had the foresight 2 years ago to add [a single line of code][1] that records claim tokens in localStorage when a run is uploaded, but simultaneously the laziness to waste two years before putting it to any use. So theoretically you can use this feature to claim runs uploaded anonymously ever since.
Would be nice to also have a page that lists claimable runs, but that's more complex.
[1]: https://github.com/glacials/splits-io/commit/191af4635d3d71f4f6cfe8e198ac67e3db676e99#diff-471b2f654e508c40fc08adf4ea19ea00R13
=> Allow claiming anonymous runs

db/migrate/20170616045119_create_doorkeeper_tables.rb, db/migrate/20170616045820_add_owner_to_application.rb
Adds version identifies to the 2 migrations missing them.
=> Remove depreciation warnings on migrations

Gemfile, Gemfile.lock
this is what rails 5 adds to the gemfile on `rails new` to remove the security warning about insecure connection with `git://` protocol
=> remove security warning on bundle install

app/controllers/api/v4/runs_controller.rb, app/models/run.rb, docs/api_v4.md, lib/parsers/livesplit.rb, lib/parsers/llanfair.rb, lib/parsers/llanfair_gered.rb, lib/parsers/splitterz.rb, lib/parsers/time_split_tracker.rb, lib/parsers/urn.rb, lib/parsers/wsplit.rb, spec/controllers/api/v4/runs_controller_spec.rb
Closes #74 .  Can also depreciate the CORS headers on `/:run_id/download/:timer`.
=> Add ability to specify accept header to retrieve runs from api

Gemfile, Gemfile.lock, config/puma.rb
Puma is the new default server in rails 5.  This commit also fixes all but one rubocop error in the gemfile
=> Switch to using puma as the default webserver

README.md, app/views/runs/_title.slim, lib/tasks/livesplit_core.rake
We just moved it over to the LiveSplit GitHub Organization, so splits.io should use these updated URLs too.
=> Move livesplit-core Repository URL

app/models/run.rb, app/models/segment.rb
This will delete all the child records by not instantiating the child records but instead deleting all of them with one query.  This means that child records of those will not be removed, but because there are no child records this doesn't apply to us.  In the even they do have child records in the future I left a comment right above it to make it clear that it needs to be changed in the event child records are added.
=> Optimize run delete queries

app/models/ability.rb, app/models/user.rb, app/views/runs/_title.slim
I had noticed that it seemed to be taking the majority of the wall clock time spent for all pages that had the title partial, so I spoofed ~11k runs locally to get larger search times locally.  This change reduced render times ~50% (usually 550ms -> 250ms) since it didn't have to load all the runs and I believe it also skips converting the active record collection to a ruby array to perform `present?`.
I also cleaned up the run title code on the title partial since it was basically duplicated since `Run.to_s` was implemented.
=> Optimize title partial rendering time

app/models/concerns/unparsed_run.rb, spec/models/run_spec.rb
Turns out we never actually saved these, no wonder they were always 0 in my testing before XD
=> Save gametime_duration_ms for each segment history entry

app/controllers/runs/stats_controller.rb
Using `order` creates a new sql query for every segment to allow the db to do the sorting, whereas `sort_by` will convert the results from preloading into a standard ruby array and sort.
=> Use sort_by instead of order to reduce queries

docker-compose-production.yml
When AWS clones in the repo, the `bin/` directory loses its executable status, which causes bundle to error on the binstub.  By passing it to ruby like you would on windows it fixes the error.
=> Fix AWS worker error

lib/speedrundotcom.rb, lib/twitch.rb
Classes don't have any idea about the module they live in, therefore it's not possible for them to be able to access or see private methods of the containing module.
Also I forgot to return ids in the follower job and when I checked I forgot to wipe the follows from the last test run so it appeared to work fine.
=> Fix 2 job errors

app/views/runs/_title.slim
It's now https://one.livesplit.org/
=> Update canonical LiveSplit One URL

app/models/concerns/srdc_run.rb, lib/speedrundotcom.rb
Rest client throws an error when the resource is not found, and since we cannot guarantee that srdc resources will still exist when users upload the file, this catches the specific error and ignores it, completing the job successfully.
SRDC does not guarantee that twitch name will be set, so account for this and return out nil if it doesn't exist instead of error'ing.
HTTPS because security and why not.
=> Fix 2 possible SRDC job errors

.travis.yml
[This comment](https://github.com/travis-ci/travis-ci/issues/5175#issuecomment-215016943) says that bash is supported even if it's not on the list if you don't want a specific language.
This saves 20-30 seconds on average per build.
=> Use bash as a language to stop ruby from installing

app/models/game.rb, app/views/runs/edit.slim, docker-compose.yml
Misattributed to pg_search, when previously looked at it was checking the wrong line.
In docker-compose this fixes running the webpack server for my VM.  For some reason with `bundle exec` it throws cannot find ruby.  It effectively does the same thing since the binstub loads everything that it needs
=> Fix sql depreciations introduced in 5.2

.example.env, .gitignore, Dockerfile, README.md, docker-compose.yml
Along with README update and addition of `.example.env`. Hooray lower friction! Hooray fewer git shenanigans!
=> Move credentials to uncommittable file

Gemfile, Gemfile.lock, app/assets/stylesheets/application.sass, app/javascript/packs/application.js, app/views/settings/index.slim, config/webpack/environment.js, package.json, yarn.lock
Fixes a bug where dropdown menus eat your first click and do nothing, requiring a second click to actually drop down.
The Dashboard theme apparently bundles base Bootstrap CSS and JS inside itself, so this was caused by us including both base JS and the theme JS, and I don't know specifically what was happening but I'm guessing attaching the same handler twice to a click is generally bad. Removing the base Bootstrap JS fixes the issue.
I also removed some leftover code from bootstrap-toggle, which is the iOS-like realtime/gametime switch currently in production (but no longer in master).
With this fix, master will be in a good state to go to production.
=> Fix dropdowns eating first click

docker-compose.yml
Will always fails since the env variables no longer exist in this container
=> Fix twitch follow sync error

Makefile
Since we use the .env file now, env variables don't pass to sudo normally, which results in them not being set.  This passes the current env variables to the sudo shell.
=> Fix env variables not passing on linux when using make commands

app/views/runs/index.slim, app/views/shared/_follows.slim
Prevents the follows table from shifting a bit to the right vs. other cards on this page by using `.p-0`. I also refactored the `.list-group` a bit to get the colors more consistent (wrapped it in a `.card`) and started using `.media` which is the supported way of putting a picture to the left of some content like this in Bootstrap. Fixes #415.
=> Fix follows alignment

config/initializers/assets.rb
The asset map would cause a 404 in development.  This adds the directory path to the asset pipeline so that it can find the map and serve it.
=> Add vendor directory to asset pipeline

Gemfile, Gemfile.lock, app/models/game.rb, app/models/user.rb, app/views/runs/index.slim, app/views/shared/_follows.slim, app/views/shared/_run_table.slim
The following is the base line setup: 7 pbs in the table, 2 of which have rivals attached to the category.  There are 3 followed runs, 2 of those have time differentials to show.
With this pr, I was able to shave ~200ms off the load time in dev env (~750ms -> 550ms), and bring the query count way down (42 uncached, 50 total -> 16 uncached, 29 total).
Let me know if you have any questions about my decisions in any parts of the code.  You could technically reduce more calls if you loaded the runs at the same time as loading the rival for the main table, but this seemed like a great start.
=> Optimize db queries on the front page

config/initializers/kaminari_config.rb
Sets max_per_page so you can't just increase the page size to infinity.  Currently the api will accept any `per_page` value, essentially allowing pagination to be bypassed.  This sets the `max_per_page` value to be 100, and if a value over that is provided 100 is simply used instead.  The `Per-Page` header in the response will also reflect the final used value if something invalid is provided.
=> Add kaminari config

app/assets/stylesheets/ads.sass, app/javascript/ad_cleanup.js, app/javascript/packs/application.js, app/views/shared/_ad.slim
Turns out the ads JS code places a div with the id `carbonads`, so I changed the holder name as well.
=> Empty ads holder before turbolinks caches page

app/models/concerns/runner_user.rb, db/schema.rb
`sum(0) do` was actually ignoring the 0 already and returning nil, so this fixes the behavior as well as correctly returning 0 from the function.  This also removes the begin statement which is redundant according to rubocop.
I also committed the removing of `google_users` table from schema file since that isn't currently on master, but if you want me to remove it let me know.
Closes #452
=> Fixes sum depreciation notice and behavior

Makefile, README.md, docker-compose.yml
This allows calls to `binding.pry` or `byebug` to be attached to instead of just ignoring them.
To attach to the instance, just run `docker attach splits-io_web_1` for the web instance, or `docker attach splits-io_worker_1`.  You can also attach to the container id found through `docker ps` if those don't work.
To detach from the container you need to exit the debug session so that execution will resume, and then do the attach escape code which is `ctrl + p` followed by `ctrl + q`.  If you do a `ctrl + c` from this you will shut down whatever the running process is (ie the web server or the worker process).
=> Expose stdin for web and worker containers

app/models/concerns/s3_run.rb, app/models/concerns/unparsed_run.rb, lib/parser/livesplit_core_parser.rb
Have `file` method change its behavior if you pass a block to it, so that it returns a file object that you can work with instead of reading the file into memory.  When the block is complete it will then close the file and clean up the tmp file that it saved down.
I also adapted the parser to check the input and if it's a `Integer` use fd parsing, otherwise fall back to the old parsing through memory.  It seemed like a good idea to keep it around for edge cases that way we don't have to add it back later.
=> Implement file descriptor based parsing

app/helpers/s3_helper.rb
Previously it did not pass in the param in the helper, this just passes it along to the concern.
=> Have space used respect `since` parameter

app/models/highlight_suggestion.rb
The current method call is the model object call which expects a parameter of either an id or array of id's to look up and destroy instead of calling it on the object that is meant to be destroyed.
=> Fix error when delaying highlight suggestion's destroy

app/models/highlight_suggestion.rb
At minimum, when reparsing a run it will re-trigger the highlight suggestion which will cause the creation to fail since it "should" get the same response back from Twitch, and find the video but since we validate on uniqueness of run_id this will cause it to not persist the suggestion, which then causes the destroy delay to fail because the object is only contained in memory.
=> Only delay destroy if highlight suggestion is persisted

app/views/layouts/application.slim
Not sure the original reason for d-none being used but I removed it and tested it through mobile and many responsive sizes.
https://github.com/glacials/splits-io/issues/462
=> Fix discord icon missing on mobile

app/models/category.rb, app/models/run.rb, app/models/speedrun_dot_com_category.rb, app/views/games/categories/_title.slim, app/views/games/categories/show.slim, app/views/runs/_title.slim, db/migrate/20190214221756_create_speedrun_dot_com_categories.rb, db/schema.rb, lib/speedrundotcom.rb
Adds associations between our categories and Speedrun.com's categories, in the same way as games from #487.
Right now, this is only used to change the button on the game/category page to link to the specific Speedrun.com category. Later, after adding Speedrun.com user links, these category links will help with powering auto-submissions to Speedrun.com.
=> Add Speedrun.com category links

app/javascript/graph_builder.js, app/javascript/packs/application.js, app/javascript/upload.js
One thing to note is that setting the size on the graphs seems to be a pretty expensive operation.  To mitigate this a bit I did 2 things: only call `chart.setSize(...)` after not receiving anymore resize events for 250ms, and defer every call to `chart.setSize(...)` so that other things can have a chance to run off the stack.  Without the defer the page totally locks up for a few seconds, whereas with it you can at least scroll and interact with the page albeit in a very limited manner until it finishes all the resizes.  Without the debounce it makes resizing simply a nightmare with how many times it tries to resize everything even when you are still dragging the window.
The previous fix with the call to `reflow()` is still required for initial page load when the graphs are collapsed.  I …
=> Add resize event handler to update segment graph sizes

app/controllers/runs/likes_controller.rb, app/views/pages/faq.slim, config/webpack/environment.js
Handlebars fix based off [this](https://github.com/wycats/handlebars.js/issues/953#issuecomment-239874313) comment.
For the `NoMethodError: undefined method 'run' for nil:NilClass`, `@run_like` will always be `nil` since we only set it in the `before_action` for the `destroy` method, but since `@run` is always defined just redirect directly back to it.
=> Fix handlebars compile warning and nil method call

.rubocop.yml, app/assets/stylesheets/brands.sass, app/controllers/runs/application_controller.rb, app/controllers/speedrun_dot_com_users_controller.rb, app/models/ability.rb, app/models/category.rb, app/models/game.rb, app/models/speedrun_dot_com_user.rb, app/models/user.rb, app/views/settings/_account_links.slim, app/views/shared/_srdc_link_modal.slim, app/views/users/show.slim, config/routes.rb, db/migrate/20190214000759_create_speedrun_dot_com_users.rb, db/schema.rb, lib/speedrundotcom.rb
Adds account links to Speedrun.com accounts. No benefit atm other than a link to your Speedrun.com profile from your Splits I/O profile page. As mentioned in #508, this is the next stepping stone to an auto-submit-to-Speedrun.com feature, and I didn't want to bundle it in the same branch since they're both pretty big features.
Speedrun.com has no OAuth support, so unfortunately we have to ask for the user's API key to do the hookup.
=> Add Speedrun.com user links

app/models/highlight_suggestion.rb
Fixes a bug where starting a PB less than 10 seconds into a stream or ending a stream less than 10 seconds after a PB would cause the highlight grabbers on Twitch to go out-of-bounds, trying to start the highlight before the video started or end it after the video ended.
=> Fix a bug where auto-highlights could OOB

app/blueprints/api/v4/run_blueprint.rb, spec/controllers/api/v4/runs_controller_spec.rb
toplevel is used on the run blueprint in v3 to verify that we want the splits to show up when accessing a run directly, but not when accessing runs in bulk on games/category pages.  v4 doesn't have this distinction.
=> Remove toplevel option from v4 blueprint and add test

app/models/concerns/unparsed_run.rb, db/migrate/20190314234116_add_filesize_to_runs.rb, db/migrate/20190315000310_backfill_add_filesize_to_runs.rb, db/schema.rb
This needs to be done in 2 stages, one to create the column and have new runs put into it, then a second to get the content length of existing runs and save that, then switch to `sum`ing the db column.
=> Store run filesize in db (1/2)

app/models/concerns/runner_user.rb, db/migrate/20190316060411_backfill_filesize.rb, db/schema.rb
Stage 2 of storing the filesize from #522 .  Backfill the actual content_length's and sum the column instead of iterating the s3 objects.
=> Store run filesize in db (2/2)

app/channels/run_channel.rb, app/controllers/runs_controller.rb, app/jobs/application_job.rb, app/jobs/broadcast_upload_job.rb, app/jobs/discover_runner_job.rb, app/jobs/highlight_cleanup_job.rb, app/jobs/refresh_game_job.rb, app/jobs/sync_user_follows_job.rb, app/models/concerns/srdc_run.rb, app/models/highlight_suggestion.rb, app/models/run.rb, app/models/twitch_user.rb, db/migrate/20190402122033_cleanup_jobs.rb, db/schema.rb, spec/models/run_spec.rb
This also includes a migration for cleaning up *most* of the broken jobs in the db.
Pros:
- First class integration with Rails
- Can change code inside job and next run will apply it (even if it errors on the first run)
- All delayed code is in one folder
Cons:
- Added complexity (more places to look for running code)
- Lose some Delayed Job specific callbacks (Rails has most of the same callbacks though)
=> Switch from delaying methods to dedicated jobs

app/models/category.rb, app/models/run.rb, app/views/games/categories/show.slim, app/views/runs/_export_button.slim, app/views/runs/_title.slim
Automatically determine the most popular route (i.e. arrangement of splits) for each category and place a download link to it on the game and category pages.
Came up with this one on the toilet an hour ago when I forgot to bring my Switch with me. TODO: Stop bringing distractions to the toilet.
=> Autoroutes

app/models/category.rb, app/models/user.rb, app/views/runs/index.slim, app/views/shared/_run_table.slim, app/views/users/show.slim
Switch is only on the profile page for a user, and allows anyone to toggle it.  Wasn't sure if it should go there or on the homepage and only allow people to see their own archived runs.
=> Add dropdown to show previous runs in pb tables

app/jobs/sync_user_follows_job.rb, app/models/highlight_suggestion.rb, app/models/twitch_user.rb, lib/twitch.rb
Start using bearer access tokens whenever possible when interacting with the Twitch API. We've been starting to hit the standard rate limit for application-scoped requests (30 / min), but by passing bearer tokens our limit goes up to 800 / user / min, I guess because it's proof we're acting on behalf of real users.
=> Use Twitch bearer tokens whenever possible

.travis.yml, docker-compose-production.yml, docker-compose.yml
Should fix our issue of log files growing infinitely big and crashing boxes.
1. Makes Rails log to its container's stdout so its logs can be managed by Docker
2. Adds log rotation to all containers
3. Also used new Docker Compose [extension fields][1] to clean up existing environment field
4. Also alphabetized compose files
5. Oh and also moved some non-secret env vars from on-box to the compose file
[1]: https://docs.docker.com/compose/compose-file/#extension-fields
=> Rotate logs

app/controllers/twitch_users_controller.rb, app/models/twitch_user.rb, app/models/user.rb, db/migrate/20190511153212_add_refresh_token_to_twitch_users.rb, db/schema.rb, lib/twitch.rb, spec/controllers/twitch_users_controller_spec.rb
Add automatic support for refreshing Twitch access tokens when they're expired or otherwise not valid.
See https://dev.twitch.tv/docs/authentication/#refreshing-access-tokens
The Twitch API has always returned refresh tokens, but access tokens never actually expired so this was never critical. I'm adding it for future proofing and to solve bugs where the access token needs refreshing for other reasons (e.g. the user changes their Twitch password).
=> Support refreshing Twitch tokens

app/jobs/broadcast_upload_job.rb, app/jobs/discover_runner_job.rb, app/jobs/highlight_cleanup_job.rb, app/jobs/refresh_game_job.rb, app/jobs/sync_user_follows_job.rb, config/application.rb, docker-compose-production.yml, docker-compose.yml
Fixes beta and production trying to process jobs enqueued by the other, which can make a box error indefinitely as it tries to run a job it doesn't know how to run.
Along with this I'll set QUEUE_PREFIX to `production` and `beta` on the respective boxes.
=> Fix poisoned queues

app/models/duration.rb
I believe I was able to keep the logic consistent with what it was before, just want to double check.  Turns out that by `including Comparable` and defining `<=>` in a certain way implements a bunch of comparing methods [automagically](https://ruby-doc.org/core-2.6/Comparable.html).
One behavior now is `Duration.new(0) != Duration.new(nil)`, and I'm not sure how that was handled before.  However `Duration.new(0) == Duration.new(0) && Duration.new(nil) == Duration.new(nil)` which I believe is new behavior?
=> Fix comparing values with nil durations

app/models/race.rb
Adds a `Race.with_ends` scope similar to `Segment.with_ends` and `SegmentHistory.with_ends`.
This method adds a computed field to the returned models called `ended_at` which contains the end time of the race, inherited from its slowest entry's finish or forfeit time (or null if at least one entry is still going).
=> Add Race.with_ends

app/views/layouts/application.slim
When using `content_for`, the string is automatically escaped and converted to a `SafeBuffer`, whoever when using string concatenation this seems to be ignored, and another round of escaping is performed.
My original fix for this was just just escape the `Game`'s string value, but I feel like we would just hit the same issue down the line with some other resource.  So instead I opted to mark the title as `html_safe`, since the (potentially user) provided titles would already have been escaped, and we control the value of `site_title`.
Closes #570
=> Fix double escaping in window titles

app/models/race.rb, app/views/games/categories/show.slim, app/views/races/index.slim, app/views/runs/index.slim, app/views/shared/_race_table.slim, app/views/users/show.slim
Fixed `finished` scope selecting races with any entrant being done, only count real entrants for abandonment purposes, race table column created -> finished.
=> Tweak race display behaviors

app/javascript/chart_builder.js, app/javascript/charts/box_plot.js, app/javascript/charts/segment.js, app/javascript/charts/segment_duration.js
Closes #527 
This takes the code from `segment.js` that ignored splits following a skipped split and moves it higher up so that all charts can use it easily. The only real complication came from the augmented object hierarchy not being mirrored in the example object used for the landing page. For the time being, I just used the original segment histories as a fallback if the filtered histories were completely missing (as they are on the landing page).
Reset Rate on Individual Segment Stats and Resets Per Split both want the unfiltered histories, so we can't just only use the filtered histories.
=> Ignore splits after a skipped split in some charts

app/models/run.rb, app/models/segment_history.rb, spec/factories/run_factory.rb, spec/factories/run_files/livesplit_skipped_splits.lss, spec/models/run_spec.rb
Closes #562.
When calculating segment_history_stats, skipped splits would cause time to accumulate in later splits.
I didn't want to turn this into a direct SQL query, but ActiveRecord was mishandling the result of the query if compiled using ActiveRecord notation for most of it, despite that fact it was generating identical raw SQL.
SegmentHistory.joins(segment: :run)
.joins(%Q{LEFT JOIN (SELECT segment_histories.id AS id, segment_histories.attempt_number AS attempt_number, segments.segment_number as segment_number FROM segment_histories INNER JOIN "segments" ON "segments"."id" = "segment_histories"."segment_id" WHERE segments.run_id = #{id} AND NOT (("segment_histories"."realtime_duration_ms" = 0 OR "segment_histories"."realtime_duration_ms" IS NULL))) AS other_histories ON …
=> Ignore segments following a skipped split when calculating segment history stats

app/blueprints/api/v4/run_history_blueprint.rb, app/javascript/charts/playtime.js, docs/api.md
Closes #473
The Effort-to-PB chart now uses `started_at` and `ended_at` from `RunHistory` to calculate playtime until a PB was reached in order to not bunch up attempts at time=0 if a user clears their splits.
I updated the API documentation, but I'm not sure how much of that is autogenerated. Additionally, I'm not sure if you want to add new fields to an existing API or not or wait until the next API version.
=> Effort-to-PB chart should use RunHistory for the x-axis

db/migrate/20190915142721_remove_video_url_from_runs.rb, db/schema.rb
This simply removes the `video_url` field from the database as part of #568 / #603. This is step 2 of 3. After this gets deployed, we can remove `self.ignored_columns = ["video_url"]` from `Run` and put `User.pbs` back to how it was.
=> Remove Run.video_url from the database

app/assets/stylesheets/timeline.sass, app/javascript/timeline.js, app/views/runs/_timeline.slim
Closes #582 
I feel like this PR is serving as a possibility, but probably not the ultimate solution. It implements @glacials's idea in #582. It works, but it feels sort of jarring as just moving your mouse around causes timelines to jump a bunch.
=> Improve split timeline comparisons

app/models/run.rb, app/models/user.rb
This removes `Run.ignored_columns` and reverts `User.pbs` to use `SELECT *` now that `Run.video_url` has been completely removed from the DB. This is the final step of  #568 / #603.
=> Remove Run.ignored_columns

Dockerfile-production, docker-compose-production.yml, docker-compose.yml, scripts/after_install.sh
Re-speed up our deploys after the docker environment changed nuked it.  I think this depends on the updated pipeline being in place first, but I don't see anything in my changes specifically that require it.  But just to be safe this should be merged after the new pipeline is set up.
=> Redo pipeline stuff for faster deploys

app/javascript/vue/race-streams.js, app/views/races/index.slim, app/views/races/show.slim
Closes #622
For such a small amount of changes this took me forever to figure out so I'll explain it for anyone else who might stumble into this.
Vue uses in place replacement by default for its `v-for` directive, which is why the last iframe was being deleted.  As far as it was concerned every div was identical so it would update the backing data and then just cut the last div.  There is a way to change this behavior though (which is highly recommended by the docs), and that is to set a `:key='xxx'` on the `v-for`.  This key needs to be unique across all elements that you are iterating over.  It can then use this to diff the iterated div and only replace those that have changed data.  However, since `template` is not an element but merely a helper, you cannot set `:key` on a template. …
=> Fix stream deck selections

app/controllers/games_controller.rb
This maintains the existing overall by-first-character sorting currently on the `games#index` page, but adds intra-character-group sorting that makes sense to people.
=> Add simple game name sorting to games#index

app/javascript/charts/run_progress.js
This addresses two problems.
1. There was a typo in using `display_name` for segments after adding segment groups.
1. If multiple segments have the same name, they will stack on the same datapoint, which sort of defeats the purpose of the chart. This fixes that.
=> Fixes category names for the Run Progress chart

app/javascript/charts/segment_duration.js, app/models/run.rb, app/models/segment_group.rb
1. Segment Groups needed `display_name` added to the values sent to charts
1. The `segment_duration` charts needed to use `display_name`
1. `SegmentHistories` with `nil` values for durations weren't being filtered out of the stats for segment groups, so it was throwing off means, segment duration charts, etc.
1. I went ahead and added sensible return values for `skipped?` and `reduced?` for `SegmentGroup`.
=> Random segment group cleanup

app/javascript/highchart_theme.js
Closes #621 
For whatever reason, scrolling charts don't use the font-family defined in the `chart.style` portion of the Highcharts options. I can't find anything about it in the documentation or online.
You can play around with it using a [JSFiddle](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/style-serif-font/) linked from the documentation and watch it break down as soon as you make the chart scroll.
This PR just specifies the font-family for a bunch of the areas that were using the Highcharts default as opposed to the specified font-family.
Shoutout to @wooferzfg for noticing it was a scrolling chart issue in Discord.
=> Fixed font issues on scrolling charts

app/models/run.rb, app/models/segment.rb, spec/factories/run_factory.rb, spec/factories/run_files/livesplit_subsplit_braces_with_no_dashes.lss, spec/factories/run_files/livesplit_subsplit_ends_with_dash.lss, spec/models/run_spec.rb, spec/models/segment_group_spec.rb
Closes #640 
There were multiple issues related to what was mentioned in #640 
1. Segments with braces without anything after the braces were throwing an exception. The fix was to no longer think those are subsplits and just display their name as is (since that's what LiveSplit does).
1. `Run.segments_with_groups` was failing when it thought a segment group had only 1 segment (the dash example @glacials mentioned in #640). That is also fixed.
If your last split starts with a dash and is the only segment in a segment group will not display exactly as it does in LiveSplit, currently. In LiveSplit, it will show the dash. That is currently not happening, but it seems minor compared to the 500 errors.
=> Fix Segment Group Issues

app/assets/stylesheets/application.sass, app/assets/stylesheets/browsersource.sass, app/controllers/races_controller.rb, app/helpers/application_helper.rb, app/views/layouts/application.slim, app/views/races/_title.slim, app/views/races/browsersource_show.slim
Adds a v1 browser source friendly layout for the race page. This is like the current race page, but:
1. Elements are resizeable by the user
2. Text is editable by the user
3. Elements have a black background with red borders and extra padding
4. UI that changes state is removed (can't chat, can't split, etc.)
The next item is to add a feed to this page with all the things we've talked about that could fuel interesting commentary during a race, but that part has some backend code and is worth its own branch.
Shoutouts to @jhobz for the red borders and padding suggestion and for spitballing the page with us :)
=> Rudimentary browser source layout for races

app/assets/stylesheets/colors.sass
Closes #666 
The issue was the `root` selector was missing a `:` before it, so the variables weren't being set properly.
FWIW, there is an [issue at libsass](https://github.com/sass/libsass/issues/2511) regarding starting a selector with a `:`. It seems to work fine in SCSS files, but not SASS files. If they get around to fixing it, we'll probably have to remove the backslash.
=> Fixes colors defined as CSS variables

.github/workflows/test.yml
Cache ruby gems and node modules between test runs.  Cuts test time by about 50% from ~11 minutes to ~5.5 minutes.
Closes #612
=> Add github actions caching

app/helpers/likes_helper.rb, app/models/concerns/unparsed_run.rb, app/views/layouts/application.slim, app/views/runs/_timing_badge.slim, app/views/runs/_title.slim, db/migrate/20200207203633_add_uses_autosplitter_to_runs.rb, db/schema.rb
Adds a badge to runs that were performed using an autosplitter:
I had trouble with the tooltip even after hard loads, so I dove a bit into solving them globally -- now that our whole site is in a Vue app container, even if we're not using Vue in a given place we can still take advantage of the Vue tippy tooltips, which show consistently regardless of soft/hard loads, so I moved the surrounding tooltips over to that style.
=> Add an autosplitter badge

spec/support/models/api/v4/segment.json
Turns out that it can indeed be null, as can be seen in this request: https://splits.io/api/v4/runs/4yrb
=> Fix `realtime_shortest_duration_ms` in API Schema

config/routes.rb
Closes #676 
It looks like even with `format: false`, it doesn't actually disable Rails's format parsing. So, this just tells Rails the `game` parameter can contain any character except for a `/`.
=> Allow any character except '/' in game name routes

app/controllers/api/v4/categories/runners_controller.rb, spec/controllers/api/v4/categories/runners_controller_spec.rb
Closes #689 
Previously, the endpoint was calling `category.users` which is just all the users through runs of a category. `category.runners` already exists and goes through a scope on `User` that is the same thing with a `distinct` tacked on. So, it's the exact thing that is desired.
=> Change the categories/runners endpoint to return unique runners

app/javascript/youtube.js, app/views/layouts/application.slim
Closes #710 
This fixes the issue where we were having to poll to see if YouTube was ready due to Turbolinks issues. Additionally, it addresses #710 and fixes problems where a YouTube player wouldn't be seen as attached to the DOM when not performing a full page load.
=> Address YouTube and Turbolinks issues

app/controllers/runs_controller.rb
If you are comparing 2 runs and the base run is shorter than the other run, the base run video progress bar won't scale properly. When you click on a segment in the shorter (faster) run, the progress bar should go to the beginning of the segment. The actual video goes to the correct place, but the bar appears ahead of where it should due to scaling off of its duration and not the duration of the longer run.
=> Properly scale the video progress bar on the timelines for comparisons

app/models/category.rb
In the current implementation, filtering by nonempty returns duplicate categories for each run associated with it. By joining the runs from the category's game, it will not return these duplicates, and each category should only appear once
=> Fix duplication when filtering by nonempty categories

Gemfile, Gemfile.lock, app/controllers/races_controller.rb, app/models/race.rb
Recently I've been wanting to split some of our more general-purpose code into gems so others can benefit from the work, and this one was a pretty straightforward candidate.
This splits off the logic that shortens race UUIDs into reversible, stateless slugs for use in URLs. It's now a gem that can be used in any Rails application on any model that has UUID primary keys. It is located at [glacials/friendly_uuid](https://github.com/glacials/friendly_uuid).
Another split I might do later is our `Duration` implementation, as it's more precise than `ActiveSupport::Duration` and has been battle tested.
There are some formatting changes included here because I'm thinking of switching us over to [ruby-formatter/rufo](https://github.com/ruby-formatter/rufo) so I'm letting it leak some changes in …
=> Split off friendly race UUIDs into its own gem

db/seeds.rb
Fixes a 500 on the logged out home page when no runs are present in the DB.
=> Add a run during seeding process

app/javascript/count.js
The default behavior of moment for object creation is to use new Date() to create the timestamp [[1]](https://momentjs.com/docs/#/parsing/now/), which pulls from the system clock.  If 2 computers are out of sync then the count down/up would be out of sync.  Switch over to calling `moment(ts.now)` which provides moment with a unix timestamp of the server's time, which is synced across all clients [[2]](https://momentjs.com/docs/#/parsing/unix-timestamp-milliseconds/).
I wasn't able to verify locally that this will fix the problem since I couldn't get the 2 devices to connect properly, but I'm fairly confident that this should fix the issue reported.
=> Use timesync instead of new Date() built in for count down/up

app/javascript/vue/SpeedRunsLiveRaceList.vue, app/views/races/_title.slim
Fixes #680 
Also load SRL logo schema-less so that it inherits from the initial page load,  fixes warning in console.
=> Add word wrap to race notes

Gemfile, app/controllers/subscription_trials_controller.rb, app/helpers/application_helper.rb, app/models/patreon_user.rb, app/models/race.rb, app/models/subscription.rb, app/models/subscription_trial.rb, app/models/twitch_user.rb, app/models/user.rb, app/views/layouts/application.slim, app/views/settings/_patreon_benefits.slim, app/views/settings/index.slim, app/views/subscriptions/index.slim, config/database.yml, config/initializers/s3.rb, config/routes.rb, db/migrate/20201123024528_create_subscription_trials.rb, db/schema.rb, docker-compose.yml, lib/twitch.rb
Currently trial subscriptions are handled completely by Stripe, and they don't have an option to allow them without entering payment information first.
This branch moves trial subscriptions to be handled by us, so that we don't need to have that requirement in place.
It also refactors the code that decides which users have which features, because it was getting pretty muddy having so many features with so many possible grantors of that feature. Now, each model that can grant a feature (Subscription, PatreonUser, and now SubscriptionTrial) has the same interface and can be easily queried en masse by User.
Also letting some more [`rufo`][1] lint leak through. I'm pretty confident I want us to switch to it.
Fixes #732.
[1]: https://github.com/ruby-formatter/rufo
=> Allow trials without credit cards

app/controllers/api/v4/speedrunslive_races_controller.rb, app/controllers/api/v4/time_controller.rb
Each time these are called we're creating a job to track them, but these are called automatically during loading of other pages so that tracking information is not really all that useful.
=> Exclude timesync and SRL endpoints from tracking
